apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifacts-
  name: ''
spec:
  entrypoint: main
  templates:
  - dag:
      tasks:
      - name: generate
        template: whalesay
      - arguments:
          artifacts:
          - from: '{{tasks.generate.outputs.artifacts.hello-art}}'
            name: message
        dependencies:
        - generate
        name: consume-artifact
        template: print-message
    name: main
  - container:
      args:
      - cowsay hello world | tee /tmp/hello_world.txt
      command:
      - sh
      - -c
      image: docker/whalesay:latest
      name: whalesay
    name: whalesay
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt
  - container:
      args:
      - cat
      - /tmp/message
      command:
      - sh
      - -c
      image: alpine:latest
      name: print-message
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    name: print-message
status: {}

