name: Python package release

on:
  release:
    types: [created]

jobs:
  release:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        sudo apt-get install tree
        # python dependencies
        python -m pip install --upgrade pip pipenv twine
        pipenv install --dev

    - name: Lint with flake8instance

      run: |
        pipenv run pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build Python package
      run: |
        pwd && tree
        pipenv run python setup.py sdist bdist_wheel

    - name: Twine check
      run: |
        pipenv run twine check dist/*

    - name: Publish to PyPI
      run: |
        pipenv run twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u macermak -p ${{ secrets.PYPI_PASSWORD }}
